// Hero frame for the Landing page.
//
// Shows a static screenshot (or SVG placeholder when no PNG is dropped at
// /public/landing/screenshot-{dark,light}.png yet) with a "Try it live"
// overlay button. Clicking the overlay navigates to /demo as a normal
// page navigation — no iframes, no nested instances of the landing page.

import { AspectRatio, Box, Card, Center, Image, useComputedColorScheme } from '@mantine/core';
import { IconPlayerPlayFilled } from '@tabler/icons-react';
import { Link } from 'react-router-dom';

export function LandingDemoFrame() {
  const computed = useComputedColorScheme('dark');

  const themeKey = computed === 'dark' ? 'dark' : 'light';
  const screenshotSrc = `/landing/screenshot-${themeKey}.png`; // PNG fallback
  // Responsive WebP candidates the browser can choose from based on its
  // viewport + DPR. Generated by `npm run screenshots` at the listed widths.
  const webpSrcSet = [800, 1200, 1600, 2400]
    .map((w) => `/landing/screenshot-${themeKey}-${w}.webp ${w}w`)
    .join(', ');
  // Tell the browser the image's *displayed* width per viewport so it can
  // pick the smallest sufficient candidate from `srcSet`. The card maxes out
  // around 1568 px (1600 - 2× 16 padding) on wide screens, otherwise ~92vw.
  const sizesAttr = '(min-width: 1600px) 1568px, 92vw';

  // Inline SVG fallback while no real screenshot is provided.
  const fallbackSvg =
    'data:image/svg+xml;utf8,' +
    encodeURIComponent(
      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 1000">
        <rect width="100%" height="100%" fill="${computed === 'dark' ? '#141416' : '#fafafa'}"/>
        <text x="50%" y="50%" fill="${computed === 'dark' ? '#71717a' : '#787774'}"
              font-family="ui-sans-serif,system-ui" font-size="36"
              text-anchor="middle" dominant-baseline="middle">
          Drop screenshot at public/landing/screenshot-${computed}.png
        </text>
      </svg>`,
    );

  return (
    <Card
      withBorder
      radius="lg"
      p={0}
      style={{
        overflow: 'hidden',
        boxShadow: '0 30px 80px rgba(0,0,0,0.25)',
        position: 'relative',
      }}
    >
      <AspectRatio ratio={16 / 10}>
        <Box style={{ position: 'relative', width: '100%', height: '100%' }}>
          {/* This is the landing page LCP element. The image is preloaded
              from index.html so the browser starts fetching during HTML parse;
              fetchpriority="high" + loading="eager" + decoding="sync" tell it
              to prioritize this image over other lazy assets on the page.
              <picture> serves WebP to modern browsers (PNG fallback for the rest). */}
          <picture style={{ position: 'absolute', inset: 0, width: '100%', height: '100%' }}>
            {/* Modern path — browser picks the smallest WebP that still
                renders crisp at its viewport × DPR. */}
            <source srcSet={webpSrcSet} sizes={sizesAttr} type="image/webp" />
            <Image
              src={screenshotSrc}
              alt="Screenshot of Reviso Notes — click to try the demo."
              fit="cover"
              fallbackSrc={fallbackSvg}
              loading="eager"
              decoding="sync"
              fetchPriority="high"
              style={{ position: 'absolute', inset: 0, width: '100%', height: '100%' }}
            />
          </picture>

          {/* Click anywhere on the screenshot to open the demo in this tab. */}
          {/* The whole gradient overlay is the link/button. The visible
              "Try it" pill is purely decorative — non-interactive and
              non-focusable so screen-reader / keyboard users get a single,
              cleanly labelled control instead of a nested focusable inside
              an aria-hidden region. */}
          <Center
            component={Link}
            to="/demo"
            style={{
              position: 'absolute',
              inset: 0,
              background: 'linear-gradient(180deg, rgba(0,0,0,0.05) 0%, rgba(0,0,0,0.35) 100%)',
              cursor: 'pointer',
              textDecoration: 'none',
            }}
            aria-label="Open the demo"
          >
            <Box
              component="span"
              role="presentation"
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 8,
                padding: '12px 20px',
                borderRadius: 9999,
                background: 'var(--mantine-color-blue-6)',
                color: '#ffffff',
                fontWeight: 600,
                fontSize: 16,
                pointerEvents: 'none',
              }}
            >
              <IconPlayerPlayFilled size={18} aria-hidden />
              Try it
            </Box>
          </Center>
        </Box>
      </AspectRatio>
    </Card>
  );
}
